name: Build and Publish Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          OWNER=${{ github.repository_owner }}
          OWNER=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          docker build . --file Dockerfile --tag ghcr.io/$OWNER/ue19-lab-05:latest

      - name: Push Docker image
        run: |
          OWNER=${{ github.repository_owner }}
          OWNER=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$OWNER/ue19-lab-05:latest
